# Generated by Django 4.2.11 on 2024-04-19 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='like_author',
            field=models.ManyToManyField(related_name='like_board', to=settings.AUTH_USER_MODEL),
        ),
    ]
