# Generated by Django 4.2.11 on 2024-04-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_like_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='like_author',
            new_name='like_authors',
        ),
    ]
