# Generated by Django 4.2.2 on 2024-03-27 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("libraries", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="category_id",
            new_name="itemId",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="category_name",
            new_name="mallType",
        ),
    ]
