# Generated by Django 4.2.2 on 2024-03-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("libraries", "0002_rename_category_id_book_itemid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="fixed_price",
            field=models.IntegerField(),
        ),
    ]
